### PR TITLE
Include start and end in time range / interval

### LINKED ISSUE #29: clarify that end of time range / interval is included (closed intervals)

### PR DESCRIPTION
**Pull request by aportagain**
Resolves #29

### CODE REVIEW

**Review by gregchalmers — COMMENTED** [review]
For me I think the following logic would make it clearer to me
`data between {start} >= and <= {end}`

**Review by delauxs — APPROVED** [review]
As per the discussion during the 105/2022 data provider catch up, this seemed to be the consensus. It makes the most sense from a user perspective

**Review by delauxs — APPROVED** [review]
Definitely no ambiguity when written that way

**Review by gregchalmers — APPROVED** [review]

**Comment by aportagain** [comment]
Andre said all good.

**Review by AndreLobato — COMMENTED** [review]
LGTM

**Pull request merged**
